
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/republic
    username: ${Database}
    password: ${Password}
  jpa:
    database: mysql
    generate-ddl: true
    show-sql: true
    properties:
      hibernate:
        format-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
  data:
    jpa:
      repositories:
        enabled: true
